services:
  windows:
    image: dockurr/windows
    restart: always
    container_name: windows
    environment:
      VERSION: "2012"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
